title: QMK Keycodes
email: yanfali@gmail.com
show_downloads: true
description: An open source firmware for AVR and ARM based keyboards
baseurl: "/keycodes"
url: "http://yanfali.github.io"
github_username: yanfali
repository: yanfali/keycodes
theme: jekyll-theme-minimal
